# config/services.yaml
parameters:

services:
    # Alias pour UserProviderInterface
    Symfony\Component\Security\Core\User\UserProviderInterface: '@security.user.provider.concrete.app_user_provider'

    App\Security\CustomAuthenticator:
        arguments:
            $passwordHasher: '@security.user_password_hasher'
            $userProvider: '@security.user.provider.concrete.app_user_provider'
            $router: '@router'
        tags:
            - { name: 'security.authenticator' }
    
    # Configuration par défaut pour les services dans ce fichier
    _defaults:
        autowire: true      # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true # Enregistre automatiquement vos services comme commandes, abonnés à des événements, etc.

    # Rend les classes dans src/ disponibles comme services
    # Cela crée un service par classe dont l'identifiant est le nom de classe entièrement qualifié
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Ajouter plus de définitions de services si une configuration explicite est nécessaire
    # Veuillez noter que les dernières définitions remplacent toujours les précédentes
